### ISSUE TITLE
Build failed with react native 0.31

### ISSUE THREAD

**Issue by smad** [inProgress-team/react-native-youtube#63]
When i try to build with RN 0.31
I've got this issue 

```
CSSLayout/CSSLayout.h' file not found with <angled> include; use "quotes" instead
CSSLayout.h:26:10: 'CSSLayout/CSSMacros.h' file not found with <angled> include; use "quotes" instead
```

I don't know what to do

Thanks

**Comment by savioseb** [comment]
Use XCode's quick fix - right click over the problem area and apply fix. It should be resolved.

**Comment by yspychala** [comment]
The XCode's quick fix solves the problem, but I use BuddyBuild with an integrated SDK and the remote build also fails and I think it's for the same reason.


```
** BUILD FAILED **
The following build commands failed:
CompileC /tmp/sandbox/57a1edef4af4710100f3aa29/bbbuild/Build/Intermediates/RCTYouTube.build/Debug-iphoneos/RCTYouTube.build/Objects-normal/armv7/RCTYouTubeManager.o RCTYouTubeManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

Is there a way to fix it?

**Comment by rpastorelle** [comment]
I don't see a "quick fix" button in Xcode 8. With Xcode 8 I needed to upgrade to RN 0.33, which breaks this plugin due to this error. Any status on a true fix yet?

**Comment by rpastorelle** [comment]
It looks like this was fixed in RN 0.34.0 (released today). See: https://github.com/facebook/react-native/commit/6e216d20343fccbb7bf9853ffb06a0d2628e9fc5

**Comment by sharnik** [comment]
I don't think it was. I'm still having the same issue on RN 0.39.2 and react-native-youtube 0.8.1. I have to do the manual xcode quick fix every time I run yarn install.

**Comment by hammadzz** [comment]
@sharnik does replacing the arrow with quotes fix it? I am having a similar issue with the react-native-material-design-kit library

**Comment by sharnik** [comment]
@hammadzz  It should. Try to open the file in XCode and use its auto-quick-fix thingy.
